In [1]:
import pandas as pd 
import wandb
import numpy as np

api = wandb.Api()
sweep = api.sweep("xingzhis/sheaf_curvature/2nrr8fvi")

sweep_runs_data = []
for run in sweep.runs:
    # Fetch run summary (metrics)
    run_data = {"id": run.id, "name": run.name}
    for key, value in run.summary.items():
        run_data["metric_" + key] = value

    # Fetch run configuration (parameters)
    for key, value in run.config.items():
        run_data["param_" + key] = value

    sweep_runs_data.append(run_data)

df = pd.DataFrame(sweep_runs_data)

their methods

In [2]:
# df_all = df[['param_path.name', 'param_path.noise', 'param_method.name', 'metric_R2', 'metric_coef', 'metric_rmse']]

In [3]:
def create_pivot_table(df, path_name, metric_name='metric_coef'):
    filtered_df = df[df['param_path.name'] == path_name]
    pivot_table = filtered_df.pivot(index='param_path.noise', columns='param_method.name', values=metric_name)
    return pivot_table

# Creating three tables for 'ellipsoid', 'hyperboloid', and 'torus'
ellipsoid_table = create_pivot_table(df, 'ellipsoid')
hyperboloid_table = create_pivot_table(df, 'hyperboloid')
torus_table = create_pivot_table(df, 'torus')

In [4]:
torus_table

param_method.name        ab        dc
param_path.noise
0.0                0.994832  0.444751
0.1                0.900682  0.270291
0.2                0.713640  0.304028
0.3                0.554378  0.308240
0.4                0.439768  0.273495
0.5                0.359890  0.242664

our method

In [5]:
sweep = api.sweep("xingzhis/sheaf_curvature/zd4y1mpo")

sweep_runs_data = []
for run in sweep.runs:
    # Fetch run summary (metrics)
    run_data = {"id": run.id, "name": run.name}
    for key, value in run.summary.items():
        run_data["metric_" + key] = value

    # Fetch run configuration (parameters)
    for key, value in run.config.items():
        run_data["param_" + key] = value

    sweep_runs_data.append(run_data)

df_ours1 = pd.DataFrame(sweep_runs_data)

In [6]:
sweep = api.sweep("xingzhis/sheaf_curvature/fkvr0ub3")

sweep_runs_data = []
for run in sweep.runs:
    # Fetch run summary (metrics)
    run_data = {"id": run.id, "name": run.name}
    for key, value in run.summary.items():
        run_data["metric_" + key] = value

    # Fetch run configuration (parameters)
    for key, value in run.config.items():
        run_data["param_" + key] = value

    sweep_runs_data.append(run_data)

df_ours2 = pd.DataFrame(sweep_runs_data)
df_ours = pd.concat([df_ours1, df_ours2])

In [7]:
(df_ours['metric_coef'] == 'NaN').mean()

0.0

In [8]:
metrics_means = df_ours.groupby(['param_path.name', 'param_path.noise', 'param_our_param.tau_radius', 'param_our_param.epsilon_PCA', 'param_our_param.max_min_num'])[['metric_non_na_percent', 'metric_coef']].mean()

In [9]:
metrics_means

                                                                                                                     metric_non_na_percent  \
param_path.name param_path.noise param_our_param.tau_radius param_our_param.epsilon_PCA param_our_param.max_min_num
ellipsoid       0.0              1                          0.2                         0.05                                        1.0000
                                                                                        0.10                                        1.0000
                                                                                        100.00                                      1.0000
                                                                                        150.00                                      1.0000
                                                                                        200.00                                      1.0000
...                                                                                                                                    ...
torus           0.5              2                          0.6                         0.05                                        0.9986
                                                                                        0.10                                        0.9986
                                                                                        100.00                                      0.9986
                                                                                        150.00                                      0.9986
                                                                                        200.00                                      0.9986

                                                                                                                     metric_coef
param_path.name param_path.noise param_our_param.tau_radius param_our_param.epsilon_PCA param_our_param.max_min_num
ellipsoid       0.0              1                          0.2                         0.05                            0.993114
                                                                                        0.10                            0.992307
                                                                                        100.00                          0.974183
                                                                                        150.00                          0.986065
                                                                                        200.00                          0.989842
...                                                                                                                          ...
torus           0.5              2                          0.6                         0.05                            0.297884
                                                                                        0.10                            0.292829
                                                                                        100.00                          0.333958
                                                                                        150.00                          0.340544
                                                                                        200.00                          0.345362

[538 rows x 2 columns]

In [10]:
metrics_means_regardless_of_data = df_ours.groupby(['param_our_param.tau_radius', 'param_our_param.epsilon_PCA', 'param_our_param.max_min_num'])[['metric_non_na_percent', 'metric_coef']].mean()

In [11]:
df_look_at = df_ours[(df_ours['param_our_param.tau_radius'] == 1) & (df_ours['param_our_param.epsilon_PCA'] == 0.2) & (df_ours['param_our_param.max_min_num'] == 200)]

In [13]:
ellipsoid_table_ours = create_pivot_table(df_look_at, 'ellipsoid')
hyperboloid_table_ours = create_pivot_table(df_look_at, 'hyperboloid')
torus_table_ours = create_pivot_table(df_look_at, 'torus')

In [14]:
ellipsoid_table_ours_non_na_rate = create_pivot_table(df_look_at, 'ellipsoid', 'metric_non_na_percent')
hyperboloid_table_ours_non_na_rate = create_pivot_table(df_look_at, 'hyperboloid', 'metric_non_na_percent')
torus_table_ours_non_na_rate = create_pivot_table(df_look_at, 'torus', 'metric_non_na_percent')

In [15]:
ellipsoid_table_ours_non_na_rate

param_method.name    ours
param_path.noise
0.0                1.0000
0.1                0.9990
0.2                0.9886
0.3                0.9762
0.4                0.9524
0.5                0.9232

In [16]:
hyperboloid_table_ours_non_na_rate

param_method.name    ours
param_path.noise
0.0                1.0000
0.1                0.9938
0.2                0.9522
0.3                0.9124
0.4                0.8716
0.5                0.8306

In [17]:
torus_table_ours_non_na_rate

param_method.name    ours
param_path.noise
0.0                1.0000
0.1                0.9996
0.2                0.9892
0.3                0.9736
0.4                0.9592
0.5                0.9358

In [18]:
pd.concat([torus_table_ours, torus_table], axis=1)

param_method.name      ours        ab        dc
param_path.noise
0.0                0.997465  0.994832  0.444751
0.1                0.677475  0.900682  0.270291
0.2                0.552229  0.713640  0.304028
0.3                0.447660  0.554378  0.308240
0.4                0.381031  0.439768  0.273495
0.5                0.316192  0.359890  0.242664

In [19]:
pd.concat([ellipsoid_table_ours, ellipsoid_table], axis=1)

param_method.name      ours        ab        dc
param_path.noise
0.0                0.989842  0.948243 -0.149432
0.1               -0.144455  0.332457  0.057116
0.2               -0.111679  0.157070  0.001588
0.3               -0.035825  0.119586  0.017359
0.4                0.011406  0.102499  0.044072
0.5                0.048354  0.099509  0.048272

In [20]:
pd.concat([hyperboloid_table_ours, hyperboloid_table], axis=1)

param_method.name      ours        ab        dc
param_path.noise
0.0                0.718362  0.712922  0.398242
0.1                0.605085  0.684188  0.332736
0.2                0.590033  0.649361  0.282134
0.3                0.537928  0.586781  0.336366
0.4                0.475771  0.529449  0.342406
0.5                0.394794  0.466885  0.326632

In [65]:
df_look_at = df_ours[(df_ours['param_our_param.tau_radius'] == 2) & (df_ours['param_our_param.epsilon_PCA'] == 0.6) & (df_ours['param_our_param.max_min_num'] == 0.10)]

In [66]:
df_best = df_look_at.groupby(['param_path.name', 'param_path.noise'])[['metric_coef']].max()
df_best.columns = ['Ours (best hyperparameters)']
df_ab = df[df['param_method.name'] == 'ab'].groupby(['param_path.name', 'param_path.noise'])[['metric_coef']].max()
df_ab.columns = ['H. & B.']
df_dc = df[df['param_method.name'] == 'dc'].groupby(['param_path.name', 'param_path.noise'])[['metric_coef']].max()
df_dc.columns = ['Diffusion Curvature']
df_compare = pd.concat([df_best, df_ab, df_dc], axis=1)
df_compare_text = df_compare.applymap(lambda x: f"{x:.3f}")

In [80]:
df_best = df_look_at.groupby(['param_path.name', 'param_path.noise'])[['metric_rmse']].max()
df_best.columns = ['Ours (best hyperparameters)']
df_ab = df[df['param_method.name'] == 'ab'].groupby(['param_path.name', 'param_path.noise'])[['metric_rmse']].max()
df_ab.columns = ['H. & B.']
df_dc = df[df['param_method.name'] == 'dc'].groupby(['param_path.name', 'param_path.noise'])[['metric_rmse']].max()
df_dc.columns = ['Diffusion Curvature']
df_compare_rmse = pd.concat([df_best, df_ab, df_dc], axis=1)
df_compare_text_rmse = df_compare_rmse.applymap(lambda x: f"{x:.3f}")

In [81]:
df_compare_text_rmse

                                 Ours (best hyperparameters) H. & B.  \
param_path.name param_path.noise
ellipsoid       0.0                                    0.430   1.052
                0.1                                    0.849  12.528
                0.2                                    1.456  30.398
                0.3                                    1.760  39.395
                0.4                                    1.988  41.153
                0.5                                    2.061  40.860
hyperboloid     0.0                                    0.293   3.954
                0.1                                    0.400   8.464
                0.2                                    0.567  20.545
                0.3                                    0.673  26.039
                0.4                                    0.753  27.437
                0.5                                    0.776  26.821
torus           0.0                                    0.864   0.753
                0.1                                    1.436  15.775
                0.2                                    1.986  32.693
                0.3                                    2.121  39.105
                0.4                                    2.143  40.709
                0.5                                    2.140  40.606

                                 Diffusion Curvature
param_path.name param_path.noise
ellipsoid       0.0                            1.134
                0.1                            1.134
                0.2                            1.134
                0.3                            1.134
                0.4                            1.134
                0.5                            1.134
hyperboloid     0.0                            0.498
                0.1                            0.498
                0.2                            0.498
                0.3                            0.498
                0.4                            0.498
                0.5                            0.498
torus           0.0                            2.269
                0.1                            2.269
                0.2                            2.269
                0.3                            2.269
                0.4                            2.269
                0.5                            2.269

In [73]:
df_compare_text

                                 Ours (best hyperparameters) H. & B.  \
param_path.name param_path.noise
ellipsoid       0.0                                    0.988   0.948
                0.1                                    0.213   0.332
                0.2                                   -0.083   0.157
                0.3                                   -0.153   0.120
                0.4                                   -0.131   0.102
                0.5                                   -0.018   0.100
hyperboloid     0.0                                    0.747   0.713
                0.1                                    0.603   0.684
                0.2                                    0.481   0.649
                0.3                                    0.428   0.587
                0.4                                    0.386   0.529
                0.5                                    0.363   0.467
torus           0.0                                    0.975   0.995
                0.1                                    0.843   0.901
                0.2                                    0.574   0.714
                0.3                                    0.342   0.554
                0.4                                    0.300   0.440
                0.5                                    0.293   0.360

                                 Diffusion Curvature
param_path.name param_path.noise
ellipsoid       0.0                           -0.149
                0.1                            0.057
                0.2                            0.002
                0.3                            0.017
                0.4                            0.044
                0.5                            0.048
hyperboloid     0.0                            0.398
                0.1                            0.333
                0.2                            0.282
                0.3                            0.336
                0.4                            0.342
                0.5                            0.327
torus           0.0                            0.445
                0.1                            0.270
                0.2                            0.304
                0.3                            0.308
                0.4                            0.273
                0.5                            0.243

In [71]:
latex_table = df_compare_text.to_latex()

In [72]:
print(latex_table)

\begin{tabular}{lllll}
\toprule
 &  & Ours (best hyperparameters) & H. & B. & Diffusion Curvature \\
param_path.name & param_path.noise &  &  &  \\
\midrule
\multirow[t]{6}{*}{ellipsoid} & 0.0 & 0.988 & 0.948 & -0.149 \\
 & 0.1 & 0.213 & 0.332 & 0.057 \\
 & 0.2 & -0.083 & 0.157 & 0.002 \\
 & 0.3 & -0.153 & 0.120 & 0.017 \\
 & 0.4 & -0.131 & 0.102 & 0.044 \\
 & 0.5 & -0.018 & 0.100 & 0.048 \\
\cline{1-5}
\multirow[t]{6}{*}{hyperboloid} & 0.0 & 0.747 & 0.713 & 0.398 \\
 & 0.1 & 0.603 & 0.684 & 0.333 \\
 & 0.2 & 0.481 & 0.649 & 0.282 \\
 & 0.3 & 0.428 & 0.587 & 0.336 \\
 & 0.4 & 0.386 & 0.529 & 0.342 \\
 & 0.5 & 0.363 & 0.467 & 0.327 \\
\cline{1-5}
\multirow[t]{6}{*}{torus} & 0.0 & 0.975 & 0.995 & 0.445 \\
 & 0.1 & 0.843 & 0.901 & 0.270 \\
 & 0.2 & 0.574 & 0.714 & 0.304 \\
 & 0.3 & 0.342 & 0.554 & 0.308 \\
 & 0.4 & 0.300 & 0.440 & 0.273 \\
 & 0.5 & 0.293 & 0.360 & 0.243 \\
\cline{1-5}
\bottomrule
\end{tabular}

In [28]:
# \begin{tabular}{llrrr}
# \toprule
#  &  & Ours (best hyperparameters) & H. & B. & Diffusion Curvature \\
# manifold & noise &  &  &  \\
# \midrule
# \multirow[t]{6}{*}{ellipsoid} & 0.0 & 0.995166 & 0.948243 & -0.149432 \\
#  & 0.1 & 0.212514 & 0.332457 & 0.057116 \\
#  & 0.2 & 0.009739 & 0.157070 & 0.001588 \\
#  & 0.3 & 0.016964 & 0.119586 & 0.017359 \\
#  & 0.4 & 0.011406 & 0.102499 & 0.044072 \\
#  & 0.5 & 0.062781 & 0.099509 & 0.048272 \\
# \cline{1-5}
# \multirow[t]{6}{*}{hyperboloid} & 0.0 & 0.808585 & 0.712922 & 0.398242 \\
#  & 0.1 & 0.698222 & 0.684188 & 0.332736 \\
#  & 0.2 & 0.629490 & 0.649361 & 0.282134 \\
#  & 0.3 & 0.566215 & 0.586781 & 0.336366 \\
#  & 0.4 & 0.504051 & 0.529449 & 0.342406 \\
#  & 0.5 & 0.459029 & 0.466885 & 0.326632 \\
# \cline{1-5}
# \multirow[t]{6}{*}{torus} & 0.0 & 0.998625 & 0.994832 & 0.444751 \\
#  & 0.1 & 0.854630 & 0.900682 & 0.270291 \\
#  & 0.2 & 0.574078 & 0.713640 & 0.304028 \\
#  & 0.3 & 0.453700 & 0.554378 & 0.308240 \\
#  & 0.4 & 0.398139 & 0.439768 & 0.273495 \\
#  & 0.5 & 0.345362 & 0.359890 & 0.242664 \\
# \cline{1-5}
# \bottomrule
# \end{tabular}

In [60]:
results = []
for group, this_df in df_ours.groupby(['param_path.name', 'param_path.noise']):
    # argbest = this_df['metric_coef'].argmax()
    argbest = this_df['metric_rmse'].argmin()
    # best = this_df['metric_coef'].max()
    # print(argbest, best)
    results.append(this_df[['param_path.name', 'param_path.noise', 'param_our_param.tau_radius', 'param_our_param.epsilon_PCA', 'param_our_param.max_min_num', 'metric_coef', 'metric_non_na_percent', 'metric_rmse', 'metric_R2']].iloc[argbest])

results_df = pd.DataFrame(results)

In [61]:
results_df

,param_path.name,param_path.noise,param_our_param.tau_radius,param_our_param.epsilon_PCA,param_our_param.max_min_num,metric_coef,metric_non_na_percent,metric_rmse,metric_R2
22,ellipsoid,0.0,1,0.6,0.10,0.989826,1.0000,0.196041,0.910145
4,ellipsoid,0.1,2,0.6,0.10,0.212514,1.0000,0.848980,-0.685168
3,ellipsoid,0.2,2,0.6,0.10,-0.083077,1.0000,1.456248,-3.958135
2,ellipsoid,0.3,2,0.6,0.10,-0.152663,1.0000,1.759826,-6.240810
1,ellipsoid,0.4,2,0.6,0.10,-0.130577,0.9994,1.988074,-8.237414
144,ellipsoid,0.5,2,0.4,0.10,0.036450,0.9928,2.054606,-8.858792
11,hyperboloid,0.0,2,0.6,0.10,0.746900,1.0000,0.292619,0.407119
9,hyperboloid,0.1,2,0.6,0.10,0.603391,1.0000,0.399646,-0.105895
10,hyperboloid,0.2,2,0.6,0.10,0.480589,1.0000,0.566606,-1.222931
8,hyperboloid,0.3,2,0.6,0.10,0.428177,0.9990,0.672999,-2.134954
6,hyperboloid,0.4,2,0.6,0.10,0.385618,0.9980,0.752937,-2.922415
7,hyperboloid,0.5,2,0.6,0.10,0.363331,0.9962,0.775518,-3.157896
357,torus,0.0,1,0.2,0.05,0.998172,1.0000,0.139406,0.995916
160,torus,0.1,2,0.4,0.10,0.854630,1.0000,1.269773,0.661193
159,torus,0.2,2,0.4,0.10,0.526148,1.0000,1.935735,0.212606
302,torus,0.3,2,0.2,0.10,0.395242,0.9736,2.044738,0.123769
301,torus,0.4,2,0.2,0.10,0.333410,0.9592,2.087492,0.089044
154,torus,0.5,2,0.4,0.10,0.276186,0.9924,2.125945,0.050241

In [53]:
df_best

                                  Ours (best hyperparameters)
param_path.name param_path.noise
ellipsoid       0.0                                  0.995166
                0.1                                  0.212514
                0.2                                  0.009739
                0.3                                  0.016964
                0.4                                  0.011406
                0.5                                  0.062781
hyperboloid     0.0                                  0.808585
                0.1                                  0.698222
                0.2                                  0.629490
                0.3                                  0.566215
                0.4                                  0.504051
                0.5                                  0.459029
torus           0.0                                  0.998625
                0.1                                  0.854630
                0.2                                  0.574078
                0.3                                  0.453700
                0.4                                  0.398139
                0.5                                  0.345362

In [62]:
df_look_at = df_ours[(df_ours['param_our_param.tau_radius'] == 2) & (df_ours['param_our_param.epsilon_PCA'] == 0.6) & (df_ours['param_our_param.max_min_num'] == 0.10)]

In [63]:
results = []
for group, this_df in df_look_at.groupby(['param_path.name', 'param_path.noise']):
    # argbest = this_df['metric_coef'].argmax()
    argbest = this_df['metric_rmse'].argmin()
    # best = this_df['metric_coef'].max()
    # print(argbest, best)
    results.append(this_df[['param_path.name', 'param_path.noise', 'param_our_param.tau_radius', 'param_our_param.epsilon_PCA', 'param_our_param.max_min_num', 'metric_coef', 'metric_non_na_percent', 'metric_rmse', 'metric_R2']].iloc[argbest])

results_df = pd.DataFrame(results)

In [64]:
results_df

,param_path.name,param_path.noise,param_our_param.tau_radius,param_our_param.epsilon_PCA,param_our_param.max_min_num,metric_coef,metric_non_na_percent,metric_rmse,metric_R2
5,ellipsoid,0.0,2,0.6,0.1,0.987982,1.0000,0.430357,0.566983
4,ellipsoid,0.1,2,0.6,0.1,0.212514,1.0000,0.848980,-0.685168
3,ellipsoid,0.2,2,0.6,0.1,-0.083077,1.0000,1.456248,-3.958135
2,ellipsoid,0.3,2,0.6,0.1,-0.152663,1.0000,1.759826,-6.240810
1,ellipsoid,0.4,2,0.6,0.1,-0.130577,0.9994,1.988074,-8.237414
0,ellipsoid,0.5,2,0.6,0.1,-0.018461,0.9988,2.061084,-8.924156
11,hyperboloid,0.0,2,0.6,0.1,0.746900,1.0000,0.292619,0.407119
9,hyperboloid,0.1,2,0.6,0.1,0.603391,1.0000,0.399646,-0.105895
10,hyperboloid,0.2,2,0.6,0.1,0.480589,1.0000,0.566606,-1.222931
8,hyperboloid,0.3,2,0.6,0.1,0.428177,0.9990,0.672999,-2.134954
6,hyperboloid,0.4,2,0.6,0.1,0.385618,0.9980,0.752937,-2.922415
7,hyperboloid,0.5,2,0.6,0.1,0.363331,0.9962,0.775518,-3.157896
18,torus,0.0,2,0.6,0.1,0.975434,1.0000,0.863851,0.843188
17,torus,0.1,2,0.6,0.1,0.843210,1.0000,1.435890,0.566746
15,torus,0.2,2,0.6,0.1,0.574078,1.0000,1.986316,0.170918
13,torus,0.3,2,0.6,0.1,0.341844,1.0000,2.121098,0.054586
14,torus,0.4,2,0.6,0.1,0.300077,1.0000,2.142841,0.035104
12,torus,0.5,2,0.6,0.1,0.292829,0.9986,2.139971,0.037460